"""init

Revision ID: a6a1635d5aae
Revises: 2f6ab825d940
Create Date: 2025-04-04 01:00:15.763662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.utils.serializers import JSONSerializable


# revision identifiers, used by Alembic.
revision: str = 'a6a1635d5aae'
down_revision: Union[str, None] = '2f6ab825d940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###